"""Active-LP research simulator interfaces and reference scaffolding."""

from research.active_lp.adversarial_search import (
    AdversarialSearchConfig,
    generate_adversarial_bundles,
    run_adversarial_search,
)
from research.active_lp.candidate_global_state import (
    CandidateGlobalStateEngine,
    CandidateInvariantChecker,
    CandidateMetricCollector,
    CandidateScenarioRunner,
    create_candidate_initial_state,
)
from research.active_lp.events import (
    BootstrapMarket,
    BuyOutcome,
    CancelMarket,
    ClaimLpFees,
    ClaimLpResidual,
    ClaimRefund,
    ClaimWinnings,
    LpEnterActive,
    ResolveMarket,
    SellOutcome,
    WithdrawLpFees,
)
from research.active_lp.fpmm_baseline import (
    FpmmBaselineEngine,
    FpmmInvariantChecker,
    FpmmMetricCollector,
    FpmmScenarioRunner,
    create_fpmm_initial_state,
)
from research.active_lp.fpmm_comparison import (
    FpmmComparisonConfig,
    build_fpmm_adversarial_config,
    build_fpmm_deterministic_bundles,
    build_fpmm_high_skew_bundles,
    run_fpmm_head_to_head,
)
from research.active_lp.metrics import CanonicalEvaluation, InvariantCheckResult
from research.active_lp.experiments import ExperimentResult, ExperimentRunner, write_experiment_results
from research.active_lp.figures import write_figure_pack
from research.active_lp.layer_c_fixed_point import (
    LayerCFixedPointEngine,
    LayerCInvariantChecker,
    LayerCMetricCollector,
    LayerCScenarioRunner,
    create_layer_c_initial_state,
)
from research.active_lp.layer_c_analysis import (
    LayerCParameterSet,
    LayerCTargetConfig,
    build_layer_c_low_tail_config,
    build_layer_c_sell_heavy_config,
    build_layer_c_target_config,
    build_layer_c_slice_rows,
    run_layer_c_parameter_sweep,
    run_layer_c_target_analysis,
    write_layer_c_analysis_pack,
)
from research.active_lp.monte_carlo import MonteCarloSweepConfig, generate_monte_carlo_bundles, run_monte_carlo_sweep
from research.active_lp.paper_artifacts import build_paper_artifacts, default_residual_weight_sources, load_residual_weight_rows
from research.active_lp.precision import DECIMAL_ONE, DECIMAL_ZERO, DEFAULT_PRECISION, high_precision, to_decimal
from research.active_lp.reporting import AggregatedReport, aggregate_results, write_aggregated_report
from research.active_lp.residual_weight_analysis import (
    ResidualWeightParameterSet,
    default_residual_weight_parameter_sets,
    run_residual_weight_sweep,
)
from research.active_lp.reference_math import (
    collateral_required,
    gauge_alpha_from_prices,
    lmsr_cost,
    lmsr_cost_delta,
    lmsr_prices,
    lmsr_sell_return,
    max_abs_diff,
    normalized_q_from_prices,
    uniform_price_vector,
)
from research.active_lp.reference_parallel_lmsr import (
    ReferenceInvariantChecker,
    ReferenceMetricCollector,
    ReferenceParallelLmsrEngine,
    ReferenceScenarioRunner,
    create_initial_state,
)
from research.active_lp.runner import InvariantChecker, MetricCollector, PricingOracle, ScenarioRunner, SimulationEngine
from research.active_lp.scenarios import (
    ScenarioBundle,
    ScenarioConfig,
    ScenarioDefinition,
    ScenarioPath,
    build_deterministic_scenario,
    build_deterministic_scenarios,
    deterministic_scenario_configs,
    deterministic_scenario_names,
)
from research.active_lp.state import MarketPricingState, SimulationState, SponsorPosition, TraderPositionBook, TreasuryState
from research.active_lp.sweep_presets import SweepPreset, build_sweep_preset, sweep_preset_names
from research.active_lp.types import EventKind, MechanismVariant, MarketStatus

__all__ = [
    "aggregate_results",
    "AggregatedReport",
    "AdversarialSearchConfig",
    "BootstrapMarket",
    "build_sweep_preset",
    "BuyOutcome",
    "CandidateGlobalStateEngine",
    "CandidateInvariantChecker",
    "CandidateMetricCollector",
    "CandidateScenarioRunner",
    "CancelMarket",
    "CanonicalEvaluation",
    "collateral_required",
    "ClaimLpFees",
    "ClaimLpResidual",
    "ClaimRefund",
    "ClaimWinnings",
    "create_initial_state",
    "create_candidate_initial_state",
    "DECIMAL_ONE",
    "DECIMAL_ZERO",
    "DEFAULT_PRECISION",
    "deterministic_scenario_configs",
    "deterministic_scenario_names",
    "EventKind",
    "ExperimentResult",
    "ExperimentRunner",
    "FpmmBaselineEngine",
    "FpmmComparisonConfig",
    "FpmmInvariantChecker",
    "FpmmMetricCollector",
    "FpmmScenarioRunner",
    "gauge_alpha_from_prices",
    "build_fpmm_adversarial_config",
    "build_fpmm_deterministic_bundles",
    "build_fpmm_high_skew_bundles",
    "generate_adversarial_bundles",
    "generate_monte_carlo_bundles",
    "high_precision",
    "InvariantCheckResult",
    "InvariantChecker",
    "lmsr_cost",
    "lmsr_cost_delta",
    "lmsr_prices",
    "lmsr_sell_return",
    "LpEnterActive",
    "LayerCFixedPointEngine",
    "LayerCInvariantChecker",
    "LayerCParameterSet",
    "LayerCMetricCollector",
    "LayerCScenarioRunner",
    "LayerCTargetConfig",
    "max_abs_diff",
    "MarketPricingState",
    "MarketStatus",
    "MechanismVariant",
    "MetricCollector",
    "MonteCarloSweepConfig",
    "normalized_q_from_prices",
    "PricingOracle",
    "ReferenceInvariantChecker",
    "ReferenceMetricCollector",
    "ReferenceParallelLmsrEngine",
    "ReferenceScenarioRunner",
    "ResidualWeightParameterSet",
    "ResolveMarket",
    "run_monte_carlo_sweep",
    "run_fpmm_head_to_head",
    "run_residual_weight_sweep",
    "create_fpmm_initial_state",
    "create_layer_c_initial_state",
    "SweepPreset",
    "ScenarioRunner",
    "ScenarioBundle",
    "ScenarioConfig",
    "ScenarioDefinition",
    "ScenarioPath",
    "SellOutcome",
    "SimulationEngine",
    "SimulationState",
    "SponsorPosition",
    "TraderPositionBook",
    "TreasuryState",
    "to_decimal",
    "uniform_price_vector",
    "WithdrawLpFees",
    "write_figure_pack",
    "write_experiment_results",
    "write_aggregated_report",
    "default_residual_weight_parameter_sets",
    "build_deterministic_scenario",
    "build_deterministic_scenarios",
    "run_adversarial_search",
    "run_layer_c_parameter_sweep",
    "run_layer_c_target_analysis",
    "sweep_preset_names",
    "build_layer_c_sell_heavy_config",
    "build_layer_c_low_tail_config",
    "build_layer_c_slice_rows",
    "build_layer_c_target_config",
    "build_paper_artifacts",
    "write_layer_c_analysis_pack",
    "default_residual_weight_sources",
    "load_residual_weight_rows",
]
